apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversation-service
  labels:
    app: conversation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversation-service
  template:
    metadata:
      labels:
        app: conversation-service
    spec:
      containers:
      - name: conversation-service
        image: ghcr.io/interviewandhealth/conversation-service:v1
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: REDIS_USERNAME
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: REDIS_PASSWORD
        - name: REDIS_URL
          value: "redis://$(REDIS_USERNAME):$(REDIS_PASSWORD)@redis-0.redis.redis.svc.cluster.local:6379/0"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: JWT_SECRET_KEY
        - name: INTERVIEW_DURATION
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: INTERVIEW_DURATION
        - name: FEEDBACK_DELAY
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: FEEDBACK_DELAY
        - name: USE_GROQ
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: USE_GROQ
        - name: MODEL
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: MODEL
        - name: GROQ_MODEL
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: GROQ_MODEL
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: GROQ_API_KEY
        - name: SPEECH_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: SPEECH_PROVIDER
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: CONVERSATION_SERVICE_AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: CONVERSATION_SERVICE_AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: CONVERSATION_SERVICE_AWS_REGION
        - name: AWS_ROLE_ARN
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: CONVERSATION_SERVICE_AWS_ROLE_ARN
        - name: AZURE_KEY
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: CONVERSATION_SERVICE_AZURE_KEY
        - name: AZURE_REGION
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: CONVERSATION_SERVICE_AZURE_REGION
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: RABBITMQ_USERNAME
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_URL
          value: "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@rabbitmq-0.rabbitmq.rabbits.svc.cluster.local:5672/"
        - name: EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: EXCHANGE_NAME
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: CONVERSATION_SERVICE_NAME
        - name: SERVICE_QUEUE
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: CONVERSATION_SERVICE_QUEUE
        - name: RPC_QUEUE
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: CONVERSATION_SERVICE_RPC
        - name: USERS_QUEUE
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: USER_SERVICE_QUEUE
        - name: USERS_RPC
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: USER_SERVICE_RPC
        - name: INTERVIEWS_SCHEDULE_QUEUE
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: INTERVIEW_SERVICE_QUEUE
        - name: INTERVIEWS_SCHEDULE_RPC
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: INTERVIEW_SERVICE_RPC
        - name: SCHEDULER_QUEUE
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: SCHEDULER_SERVICE_QUEUE
---
apiVersion: v1
kind: Service
metadata:
  name: conversation-service
spec:
  selector:
    app: conversation-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000