apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-service
  labels:
    app: scheduler-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-service
  template:
    metadata:
      labels:
        app: scheduler-service
    spec:
      containers:
      - name: scheduler-service
        image: ghcr.io/interviewandhealth/scheduler-service:v1
        env:
        - name: REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: REDIS_USERNAME
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: REDIS_PASSWORD
        - name: REDIS_URL
          value: "redis://$(REDIS_USERNAME):$(REDIS_PASSWORD)@redis-0.redis.redis.svc.cluster.local:6379/0"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: RABBITMQ_USERNAME
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_URL
          value: "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@rabbitmq-0.rabbitmq.rabbits.svc.cluster.local:5672/"
        - name: EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: EXCHANGE_NAME
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: SCHEDULER_SERVICE_NAME
        - name: SERVICE_QUEUE
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: SCHEDULER_SERVICE_QUEUE