apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: ghcr.io/interviewandhealth/user-service:v2
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@postgres-0.postgres.postgres.svc.cluster.local:5432"
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: USER_SERVICE_DB
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: JWT_SECRET_KEY
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: RABBITMQ_USERNAME
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_URL
          value: "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@rabbitmq-0.rabbitmq.rabbits.svc.cluster.local:5672/"
        - name: EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: EXCHANGE_NAME
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: USER_SERVICE_NAME
        - name: SERVICE_QUEUE
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: USER_SERVICE_QUEUE
        - name: RPC_QUEUE
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: USER_SERVICE_RPC
        - name: INTERVIEW_QUEUE
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: INTERVIEW_SERVICE_QUEUE
        - name: INTERVIEW_RPC
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: INTERVIEW_SERVICE_RPC
        - name: PAYMENT_QUEUE
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: PAYMENT_SERVICE_QUEUE
        - name: PAYMENT_RPC
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: PAYMENT_SERVICE_RPC
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: GOOGLE_CLIENT_SECRET
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: USER_SERVICE_AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: USER_SERVICE_AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: USER_SERVICE_AWS_REGION
        - name: AWS_S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: USER_SERVICE_AWS_S3_BUCKET_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000