apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    REDIS_PASSWORD: AgAR6vxfaSV9EaI5JMBhyHkwct8keujXaOEvGEyOGeTs8LYKLhbvFpdYEQ2yK8W0WbOzFE6sWhATIAkyCmkGUMZkwnwSEhqWZzTt/FQAov4lcjUBtNbgJMzthyiV+/X9tawSaA+/ONOmD2InHBTiN8HNI2o26gVLvNhPU/5Ad1xYUlDn2wKJCTVDInL6E9o8pq6lse7hXp62NA65Tyf2GM4S0Fjowv2G3MX6L2o+Ksi5rnC6Ll8gtBb3F0pQ6jrSBEiyy0HsX8VDuzsWDbgEhTDpqdtlxH+SW0rYdUXztETscGvYaZ8whPKbSeNecMzTRZVK3NTSko6bByoQbfJZgkMr0MgbLh3vN8sJFV6mwDZ4ZInvZ0HIAG6C2Nq61JinXHwZKm1Uw00qJ8wlhRur5S8oYsHcj5+53NY0OdtjKGEUlZ0BERPl4guT5Wo+8NtfrUv9oHK87RYS9onV/X31lth68lBhN14024Pp1O8V/m68YQkotIdEm1EbuK8J63qjIfWZ33dTyXAoSVprY0ETcmTJgiTwnQmGcO3AKQ+dCHabqmyfB2uhcj5rlvGSm0wGQLN2RqnKvqCBe1qw/1/f8JgnQZLJa+WMyNFYgWbzwsKTZw1R7GCXwRbHEvL+L/KsQMqETSw3lVhaZfLV3415Srl58vi38vEEH59R5aKAM8pKWcY6OlymeO2Wb7btKj03TUWMRQEo6mJVRruKmKJEbb8H5ZyuY+Pg+FmPl5hnbAZPBQ==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: redis
    type: Opaque
