apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: kube-system
spec:
  encryptedData:
    access_key: AgBz81b17Jo98iWdq7OaDU/H9Aq3Ewi4ufz3kcJ0/JSoLuP0BHAvl88Q8MaQMh0C007UUptuW7FfAZ1pGOkTSq0GbqoNZKUCzpxi5ta44zJb0Nz6m5HoiH1h6RgeQLSBvFl5EbwhnMYqkAp30GcmVjNmMv/SYQEglMHKNOK5TgH5hwvBXwy0Y4V+QY3EAv98R58JP/ZMpHLBOwn0g5/jk/SEDXk9xg+trkeh/3i+PhXCfoP6oIHSjVycMo5O9sr8xJrjf5VFFkaMUfT0i8ML+dIZmI3V6Hvx5leL2V3UJQWLu2TOIMnnZn9f6mLI6v57eS4BOwdAHENZNLWgIPbNqEJ7XBeuwS+h8PTS6laZIoQ1LBxbrkAWucC7BPi2c9wRxck/F5q+yt46DqkTuQ54FRdg4OV71gpqWi9/1tS6eGat37ggQCuSbhY4q21VXG7KdU6xRogJR2fL7ntDkb4DmRjk3pcdnR62WbIiln4e0/fm1hTKFoMkYJyjByElC12jlVglhrmqjYmbXZ5Hk6ZbUxJwN3MF97DZQIKkfecQpnYlmQFsGxBfDevxO7PuIrWKkjV+N2H9s2XhrLlypnwSikdCiHgPl5ga1ElymQz4fC+azWVl0v9C4w+EjTEZXR8B6IxitU7VQjx7lZTMcUzEM6CJKD7H2amfVoMZp22MZqs/Af8abbPsSkdzYkEmy2YV7CovMnuZfefVIgDeOQB7z3S5ZSTzuRpXWiWjA2mXLUlxX3/98jCP6+vW
    key_id: AgAWaii+W4dYvEeXnTrBCTdGOek3Bs05qY8Mp1mAUH0mWYfFpgUgmnTZY4oBKnALUd4Pf7f7LOIDeYakoQ06roNIaXrZ9Wbed3kXR1O7WgHzRjKcYYNU5kf7wv0P7AW6CuLaE6E3hFJr7B5fESlFB9zlbsaC9cmF3xaXVwIB/mttcfOJ2CqRdoh4RI2OqGcnWjS6Cc/LRr5QtbTRyXa2d0M0Rm1oIjVMOEsXI8N14HqQjZRKnUFVcbJusdi/a3fY+aLsY4Uls8uMGktWSua6TRpZiAPwEJ5vqmA6PIWCz4ga/a+94CEPXqKaHC9BDhS5og/RQwAcVgUxKF1UABQygiPN+iDWKP4DvQkDlBRa51ZpXclWGD80ThYFuFHX8pNx8gXz/ktzCzLlHpevGqoJRiUgc9c4EZ5flgtFNAHjYVu5iBWR1wayuIc6OPT9g82t5SiiBtERIP9OVzws2FIMobyyHt+Xyz5BV09cMx3k9huTsn0gUOOfKpA/D6wYUIl6HAXr0vE7X2cXnFPOXQvNe4yR07wEr8PEaQozWm/0QYQeXBv152HpcehBN3qOFiZUOlwDvbPc0kubuKJocEyZ+2VDKAiITFHm+h5TFb4F3JtZePns+8TUkle3lcYaix2gD7FsTI77SVbGDwb6pFO9gO5qJA7KnbMrxjSu7zZ1apIgjMb7QCyXooSM80tRuRPzUGX59DrNtr0OWHAkSrS1xJQfGpdEXA==
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: kube-system
    type: Opaque
