apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: kube-system
spec:
  encryptedData:
    access_key: AgAfYOqTpJ6GaxImBWRNhO29BJVYOh4RxP8ttspxoVpdghaJXoIgd2/idp1dvnu7BNgGnsJbYC8lxiRiijB+c0qVLY4buMCjTZ+9SxTwSZVJPF9KAXB1kJGM7aIqjOMZjvi3wqJ9vYNKINNZH2vQKD7zGh14wK1C6H9FSJdjXAzCTLt8N3JXPiofpPTohNYKUeR2OD5p6wjUxSgkhqZqPIyuMu1TLUGbYIhiyvLg9lCdhgaiWl3pHTXXwuV9N7NASYBYPbC5Dw2fbAEZN26eA1ivkZ+3cK+Gsj6LGBmG7Vizo06dML4ssA4KVA/9TlPazqP/4r3LjHVtw7owGq38JjeJC5o5U1y9qPPd4poXCbdgolF0kaTcCRn7uuxEoM/nBO/OoTL4E2NTZctXVVa6t3T27g2NHbsKBXZfAeHKJvtqgLRmLc5skOzYwzQWDIZszkPRlx/BiQnQPbzuhxGyBOYVvIFoHWIbVuXtrCwSD5bDlmQggsWUtFcFvQLP5TDPZhKjdvPIhPJGBGBPieKDjefsjr+coFoDOwH6p5/JBFyjyvvIPNoc5obfWxjcXuriynGKnfYFzAp7eDihh67fIaqRH05ZQLG3Fx+faTNVMtc1FQmisgdpPeH56QD6gEoKxRrhBd7Dso9vKsfsaQAhOzsKa1mASuazVhv6P4KRr3PEEYOttepgPswlnZhOunPgE42mBvvHHUEZOoO23y8kYCwiM79FLPWDehhOTf4IwsviqA77P7c7jqzN
    key_id: AgCLnkvI8BUoGXFIxW7LEpp2fpdfUjAcavz5EzGirvknZkIflXklJJlINn53uh8KL324vXnWy8pS09QltdZ6rHvtMLdgmDEBZoxYtUXIfqCIHmXJlXP77fBe9cM3E4bStLc/VKG4Y0ANmHoLL8v1AqVaXGm17Y5OIps04QyUMsajDruA2gSfMWHq0OtF3tclrDq+lb5HeAzXtaJeXA5ohSbcJyyfpqUHcVs+CJSnpyiMLagj/iNyeaHiXaw2r9Op3q6K4T4vix9PclHckzShR8MS8+eVZl89a1qghQERUH76RAgMe9W8SCRQfOXkNEoGX60vMlg+Td17yu5UK5i5PmuI3kgJ+n6QfBPQy6BYOUFMo2woVHNiythoc1wawwJ7Z6JPIgrUqj8c7deOgdfQhpfmzfu46eefBE925lK03rceznJTVaBApSKwqW/eQWbuInreuzQJdn5ReO+Lo6uHhN7ot8g1ssCBw+VHzjmiZQznGZ74mMjB4bcnBXpFjYwKXCsRVSJiol73W3yvHyGAyPjokk0fztxdkYO+ujrXI7r/conoRv1AHOqcFTYPYPSEAbuNe4b5ugOHEjDEypCtH01o2CIRcMlYVgNykYKsaWlFnyISme4IqNPLwTW/EL0ylSMznWarSYP1a+sRf0wNBQnq/ELb0+JqC35gMmD5n0UJthVHVHdgy24VEe11u/VLjjkFvfD4u+yPxxMfieQl2g0glXYLPQ==
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: kube-system
    type: Opaque
